// Refer to a list of all possible actions
export const REQUEST_NEW_RELEASES = 'REQUEST_NEW_RELEASES';
export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES';
export const RECEIVE_NEW_RELEASES = 'RECEIVE_NEW_RELEASES';
export const SET_COUNTRY_ID = 'SET_COUNTRY_ID';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const REQUEST_PLAYLIST = 'REQUEST_PLAYLIST';
export const RECEIVE_PLAYLIST = 'RECEIVE_PLAYLIST';